mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    # account_login, account_logout, account_set_password
    path('accounts/', include('allauth.urls')),
    path('register/', include('authen.urls')),
    path('taskmaster/', include('taskmaster.urls'))
]

mysite/taskmaster/urls.py
from django.urls import path
from . import views


app_name = 'taskmaster'
urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('master/', views.MasterView.as_view(), name="master"),
    path('master/create/', views.MasterCreateView.as_view(), name="master_create"),
    path('master/<int:pk>/detail', views.MasterDetailView.as_view(), name="master_detail"),
    path('master/<int:pk>/update/', views.MasterUpdateView.as_view(), name="master_update"),
    path('master/<int:pk>/delete/', views.MasterDeleteView.as_view(), name="master_delete"),
    
    path('task/', views.InboxView.as_view(), name="inbox"),
    path('task/create/', views.TaskCreateView.as_view(), name="task_create"),
    path('task/<int:pk>/update/', views.TaskUpdateView.as_view(), name="task_update"),
    path('task/<int:pk>/detail/', views.TaskDetailView.as_view(), name="task_detail"),
]

mysite/taskmaster/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='todolist', null=False)
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    class Priority(models.TextChoices):
        P1 = "!", _('WAITING')
        P2 = "!!", _('TODO')
        P3 = "!!!", _('URGENT')

    todolist = models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    priority = models.CharField(max_length=3, choices=Priority.choices, default=Priority.P1)
    created_at = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    due_date = models.DateTimeField(null=True)
    complete = models.BooleanField(default="False")

    def __str__(self):
        return self.name

mysite/taskmaster/forms.py
from django import forms
from .models import ToDoList, Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'description', 'due_date', 'todolist', 'priority']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['todolist'].queryset = self.fields['todolist'].queryset.filter(user=user)

mysite/taskmaster/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from .models import ToDoList, Item
from .forms import ItemForm

import datetime


class HomeView(LoginRequiredMixin, View):
    def get(self, request):
        task_list = []
        try:
            todolist = get_list_or_404(ToDoList, user=request.user)
        except Http404:
            todolist = []
        for master in todolist:
            for task in master.item_set.all():
                if task.complete == False:
                    task_list.append(task)

        task_list = sorted(task_list, key=lambda x: x.due_date)
        current_time = datetime.datetime.now()
        ctx = {'tasks': task_list, 'time': current_time}
        return render(request, 'taskmaster/home.html', ctx)

    def post(self, request):
        task_list = []
        try:
            todolist = get_list_or_404(ToDoList, user=request.user)
        except Http404:
            todolist = []
        for master in todolist:
            for task in master.item_set.all():
                if not task.complete:
                    task_list.append(task)

        if request.POST.get("update"):
            for task in task_list:
                if request.POST.get('t' + str(task.id)) == "completed":
                    task.complete = True
                task.save()

        task_list = sorted(task_list, key=lambda x: x.due_date)
        current_time = datetime.datetime.now()
        ctx = {'tasks': task_list}
        return render(request, 'taskmaster/home.html', ctx)


class MasterView(LoginRequiredMixin, View):
    def get(self, request):
        try:
            master_lists = get_list_or_404(ToDoList, user=request.user)
        except Http404:
            master_lists = []

        ctx = {'masters': master_lists}
        return render(request, 'taskmaster/master.html', ctx)


class TaskView(LoginRequiredMixin, View):
    def get(self, request, pk):
        task_list = []
        try:
            master = get_object_or_404(ToDoList, id=pk, user=request.user)
        except Http404:
            master = []
        for task in master.item_set.all():
            task_list.append(task)

        task_list = sorted(task_list, key=lambda x: x.due_date)
        ctx = {'master': master, 'tasks': task_list}
        return render(request, 'taskmaster/item_list.html', ctx)


class InboxView(LoginRequiredMixin, View):
    def get(self, request):
        task_list = []
        try:
            todolist = get_list_or_404(ToDoList, user=request.user)
        except Http404:
            todolist = []
        for master in todolist:
            for task in master.item_set.all():
                task_list.append(task)
        
        task_list = sorted(task_list, key=lambda x: x.due_date)
        current_time = datetime.datetime.now()
        ctx = {'tasks': task_list, 'time': current_time}
        return render(request, 'taskmaster/inbox.html', ctx)

    def post(self, request):
        task_list = []
        try:
            todolist = get_list_or_404(ToDoList, user=request.user)
        except Http404:
            todolist = []

        for master in todolist:
            for task in master.item_set.all():
                task_list.append(task)

        task_list = sorted(task_list, key=lambda x: x.due_date)
        ctx = {'tasks': task_list}
        if request.POST.get("update"):
            for task in task_list:
                if request.POST.get('t' + str(task.id)) == "completed":
                    task.complete = True
                else:
                    task.complete = False
                task.save()
        return render(request, 'taskmaster/inbox.html', ctx)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('taskmaster:inbox')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Item 


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('taskmaster:inbox')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class MasterDetailView(LoginRequiredMixin, DetailView):
    model = ToDoList 

    def post(self, request, pk):
        task_list = []
        todolist = get_object_or_404(ToDoList, id=pk)
        print(todolist)
        for task in todolist.item_set.all():
            task_list.append(task)
     
        if request.POST.get("update"):
            for task in task_list:
                if request.POST.get('t' + str(task.id)) :
                    task.complete = True
                else:
                    task.complete = False
                task.save()

        return HttpResponseRedirect(reverse('taskmaster:master_detail', kwargs={'pk':pk})) 


class MasterCreateView(LoginRequiredMixin, CreateView):
    model = ToDoList
    fields = ['name']
    success_url = reverse_lazy('taskmaster:master')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class MasterUpdateView(LoginRequiredMixin, UpdateView):
    model = ToDoList
    fields = ['name']
    success_url = reverse_lazy('taskmaster:master')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class MasterDeleteView(LoginRequiredMixin, DeleteView):
    model = ToDoList
    fields = '__all__'
    success_url = reverse_lazy('taskmaster:master')

mysite/taskmaster/templates/taskmaster/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'taskmaster/w3.css' %}">
    <title>Task Master | {% block pagetitle %}{% endblock %}</title>
</head>

<body>
    <div class="w3-sidebar w3-bar-block w3-deep-purple w3-border-right" style="width:15%">
      <a href="{% url 'taskmaster:home' %}" class="w3-bar-item w3-margin-bottom">
        <img src="{% static 'taskmaster/img/taskmaster.png' %}" alt="Brand Logo" style="width:100%;">
      </a>
      <a href="{% url 'taskmaster:home' %}" class="w3-bar-item w3-button w3-large w3-hover-white">Home</a>
      <a href="{% url 'taskmaster:inbox' %}" class="w3-bar-item w3-button w3-large w3-hover-white">Inbox</a>
      <a href="{% url 'taskmaster:master' %}" class="w3-bar-item w3-button w3-large w3-hover-white">Masterlists</a>
    </div>

    <div style="height:100vh;margin-left:15%;">
      <div class="w3-bar w3-light-grey w3-padding-small">
        <span class="w3-bar-item w3-left">
          {% block pagename %}{% endblock %}
        </span>
        
        {% if user.is_authenticated %}
          <a href="{% url 'account_logout' %}" class="w3-bar-item w3-button w3-round w3-pink w3-border w3-border-pink w3-hover-white w3-right">
            <b>Log Out</b>
          </a>
          <a href="{% url 'taskmaster:task_create' %}" class="w3-bar-item w3-button w3-margin-right w3-round w3-deep-purple w3-border w3-border-deep-purple w3-hover-white w3-right"><b>+ New Task</b></a>
      
        {% else %}
          <a href="{% url 'account_signup' %}" class="w3-bar-item w3-button w3-round w3-yellow w3-border w3-border-yellow w3-hover-white w3-right w3-margin-left">
            <b>Sign Up</b>
          </a>
          <a href="{% url 'account_login' %}" class="w3-bar-item w3-button w3-round w3-deep-purple w3-border w3-border-deep-purple w3-hover-white w3-right">
            <b>Log In</b>
          </a>
        {% endif %}
      </div>
        

      <div class="w3-container w3-white">

        {% block info %}
        {% endblock info %}

        {% block content %}
        {% endblock %}
        
      </div>

    </div>
</body>
</html>

mysite/taskmaster/templates/taskmaster/home.html
{% extends 'taskmaster/base.html' %}

{% block pagetitle %}
	Home
{% endblock %}

{% block pagename %}
    <span class="w3-badge w3-xlarge w3-deep-purple">
        😎
    </span>
    <span class="w3-text-deep-purple">
        <b>{{user.username|capfirst}}</b>
    </span>
{% endblock %}

{% block info %}
    <div class="w3-panel w3-round w3-border w3-padding w3-text-deep-purple">
        <h3><b>
        {% if time.hour < 12 %}
            Good morning
        {% elif time.hour <= 17 %}
            Good Afternoon
        {% else %}
            Good Evening
        {% endif %}
        , {{user.username|capfirst}}
        </b></h3>
        <div class="w3-leftbar w3-border-green w3-pale-green w3-round w3-padding">
        This is your homepage where you can quickly see your upcoming tasks.
        </div>
    </div>
{% endblock info %}

{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    <div class="w3-display-container w3-text-deep-purple w3-bottombar w3-border-deep-purple">
        <h3>🎯 Upcoming Tasks</h3>
        <button type="submit" class="w3-btn w3-round w3-deep-purple w3-border w3-border-deep-purple w3-hover-white w3-display-right" name="update" value="true">Update</button>
    </div>
    {% if tasks %}
    <div class="w3-light-grey w3-container" style="height:300px;overflow-y:scroll;">
        <div class="w3-row-padding">
            {% for task in tasks %}
            <div class="w3-col l6">
                <div class="w3-card w3-white w3-section w3-leftbar w3-border-amber w3-padding">
                    {% if task.complete %}
                        <input type="checkbox" name="t{{task.id}}" value="completed" class="w3-check" checked>
                    {% else %}
                        <input type="checkbox" name="t{{task.id}}" value="completed" class="w3-check" >
                    {% endif %}
                    
                    <a href="{% url 'taskmaster:task_detail' task.id %}" class="w3-margin-left w3-text-deep-purple w3-large"><b>{{task.name}}</b></a> 
                    
                    <span class="w3-tag w3-round w3-pink w3-right w3-xlarge">{{task.priority}}</span>

                    <div class="w3-cell-row w3-round w3-border w3-section" style="width:auto">
                        <span class="w3-cell">
                            ⏰
                        </span>
                        <span class="w3-cell w3-light-grey">
                            <b>{{task.due_date}}</b>
                        </span>
                    </div>
                     <a href="{% url 'taskmaster:master_detail' task.todolist.id %}" class="w3-btn w3-green w3-border w3-hover-white">{{task.todolist}}</a>
                </div>
            </div>
            {% endfor %}
            </div>
    </div>
    {% else %}
    <div class="w3-panel w3-leftbar w3-border-amber w3-yellow w3-large w3-padding w3-round">
        Everything is done! If you have some tasks on your mind, add by clicking <span class="w3-tag w3-deep-purple w3-round">+NewTask</span> button.
    </div>
    {% endif %}
    </form>
{% endblock %}

        {# <h2 class="w3-text-deep-purple w3-center">Welcome to
        <span class="w3-tag w3-round w3-deep-purple">TASKMASTER</span>
        </h2>
        <div class="w3-panel w3-leftbar w3-border-deep-purple w3-round w3-light-grey w3-padding">You're not logged in right now. Log in to organize your tasks and become the most productive person ever. If you don't have an account yet, set up your account in just a few minute.
        </div>
        <a href="{% url 'register:register' %}" class="w3-btn w3-round w3-margin w3-yellow w3-border w3-small w3-border-yellow w3-hover-white">Get Started for FREE</a>

        <a href="{% url 'login' %}" class="w3-btn w3-deep-purple w3-border w3-small w3-border-deep-purple w3-hover-white">Log In to Existing Account</a> #}

    

mysite/taskmaster/templates/taskmaster/inbox.html
{% extends 'taskmaster/base.html' %}

{% block pagetitle %}
	Inbox
{% endblock %}

{% block pagename %}
	<span class="w3-badge w3-xlarge w3-deep-purple">
        😎
    </span>
    <span class="w3-text-deep-purple">
        <b>{{user.username|capfirst}}</b>
    </span>
{% endblock %}

{% block info %}
    <div class="w3-panel w3-round w3-border w3-padding w3-text-deep-purple">
        <h3><b>
        {% if time.hour < 12 %}
            Good morning
        {% elif time.hour <= 17 %}
            Good Afternoon
        {% else %}
            Good Evening
        {% endif %}
        , {{user.username|capfirst}}
        </b></h3>
        <div class="w3-leftbar w3-border-green w3-pale-green w3-round w3-padding">
        In this <b>Inbox</b>, all of your completed and upcoming tasks can be seen.
        </div>
    </div>
{% endblock info %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="w3-display-container w3-text-deep-purple w3-bottombar w3-border-deep-purple">
            <h3>📦 All Tasks</h3>
            <button type="submit" class="w3-btn w3-round w3-deep-purple w3-border w3-border-deep-purple w3-hover-white w3-display-right" name="update" value="true">Update</button>
    </div>
    {% if tasks %}
    <div class="w3-light-grey w3-container" style="height:300px;overflow-y:scroll;">
    <ul class="w3-ul" style="width:80%;margin:auto">
            {% for task in tasks %}
                <li class="w3-card w3-white w3-section w3-leftbar w3-border-amber w3-padding">
                    {% if task.complete %}
                        <input type="checkbox" name="t{{task.id}}" value="completed" class="w3-check" checked>
                    {% else %}
                        <input type="checkbox" name="t{{task.id}}" value="completed" class="w3-check" >
                    {% endif %}
                    
                    <a href="{% url 'taskmaster:task_detail' task.id %}" class="w3-margin-left w3-text-deep-purple w3-large"><b>{{task.name}}</b></a> 
                    <span class="w3-tag w3-round w3-pink w3-right w3-large">{{task.priority}}</span>

                    <div class="w3-container w3-margin-top w3-small">
                        <span class="w3-tag w3-round w3-green">{{task.todolist}}</span>
                        <span class="w3-tag w3-round w3-purple">{{task.due_date}}</span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    <div>
    {% else %}
    <div class="w3-panel w3-yellow w3-leftbar w3-border-amber w3-large w3-round">
        <p>You don't have any task added yet. Click <span class="w3-tag w3-deep-purple w3-round">+NewTask</span> button to add new task.</p>
    </div>
    {% endif %}
</form>

{% endblock %}

mysite/taskmaster/templates/taskmaster/item_detail.html
{% extends "taskmaster/base.html" %}
{% block pagetitle %}
	Task Detail
{% endblock pagetitle %}

{% block pagename %}
	<span class="w3-badge w3-xlarge w3-deep-purple">
        😎
    </span>
    <span class="w3-text-deep-purple">
        <b>{{user.username|capfirst}}</b>
    </span>
{% endblock pagename %}

{% block content %}
<div class="w3-card-4 w3-section w3-round" style="width:80%;margin:auto;">
	<div class="w3-bar w3-deep-purple w3-padding">
		<div class="w3-bar-item w3-xlarge"><b><i>{{item.name}}</i></b></div>
		<a href="{% url 'taskmaster:task_update' item.id %}" class="w3-btn w3-white w3-border w3-border-purple  w3-text-deep-purple w3-hover-purple w3-round w3-bar-item w3-right">Edit</a>
	</div>
	<div class="w3-container w3-padding w3-text-deep-purple">
		<span class="w3-tag w3-small w3-yellow w3-round">Created at: {{item.created_at}}</span></p>
		{% if item.description %}
			<div class="w3-panel w3-leftbar w3-round w3-border-blue-grey w3-light-grey w3-padding w3-cursive w3-text-deep-purple"><b>{{item.description}}</b>
			</div>
		{% endif %}
		<div class="w3-bar w3-margin-bottom">
			<div class="w3-bar-item w3-light-grey w3-margin-right" style="width:30%"><b>Priority : </b></div>
			<div class="w3-bar-item w3-tag  w3-pink w3-round-large"><b>{{item.priority}}</b></div>
		</div>
		
		<div class="w3-bar w3-margin-bottom">
			<div class="w3-bar-item w3-light-grey w3-margin-right" style="width:30%"><b>Due Date : 
		</b></div>
			<div class="w3-bar-item w3-round w3-border">
				<b>{{item.due_date.date}} </b>
				<span class="w3-tag w3-round-large w3-dark-grey">
					{{item.due_date.time}}
				</span>
			</div>
		</div>

		<div class="w3-bar">
			<div class="w3-bar-item w3-light-grey w3-margin-right" style="width:30%"><b>Master : </b>
			</div>
			<a href="{% url 'taskmaster:master_detail' item.todolist.id %}" class="w3-button w3-bar-item w3-deep-purple w3-hover-purple">{{item.todolist}}</a>
		</div>
	</div>
</div>
{% endblock content %}

mysite/taskmaster/templates/taskmaster/item_form.html
{% extends 'taskmaster/base.html' %}
{% load widget_tweaks %}
{% block pagetitle %}
	New Task
{% endblock pagetitle %}
{% block pagename %}
	<span class="w3-badge w3-xlarge w3-deep-purple">
        😎
    </span>
    <span class="w3-text-deep-purple">
        <b>{{user.username|capfirst}}</b>
    </span>
{% endblock pagename %}
{% block content %}
<div class="w3-card-4 w3-round" >
	<div class="w3-deep-purple">
		{% if item %}
			<h2 class="w3-padding">Edit Task</h2>
		{% else %}
			<h2 class="w3-padding">Create New Task</h2>
		{% endif %}
	</div>
	<form method="post" class="w3-container">
		{% csrf_token %}
		<div class="w3-cell-row w3">
			<div class="w3-cell w3-padding" style="width:70%;">
				<label class="w3-text-deep-purple"><b>Task:</b></label>
				{{form.name | add_class:"w3-input w3-border"}}
			</div>
			<div class="w3-cell w3-padding">
			<label class="w3-text-deep-purple"><b>Category:</b></label>
			{{form.todolist | add_class:"w3-select w3-border"}}
		</div>
		</div>
		<div class="w3-padding">
			<label class="w3-text-deep-purple"><b>Description:</b></label>
			{{form.description | add_class:"w3-input w3-border"}}
		</div>
		<div class="w3-cell-row w3-section">
			<div class="w3-cell w3-padding">
				<label class="w3-text-deep-purple"><b>Due Date:</b></label>
				{% render_field form.due_date type="datetime-local" class+="w3-input w3-border" %}
			</div>
			<div class="w3-cell w3-padding">
				<label class="w3-text-deep-purple"><b>Priority:</b></label>
				{{form.priority | add_class:"w3-select w3-border"}}
			</div>
		</div>
		<div class="w3-right w3-margin-bottom">
			<a href="{% url 'taskmaster:master' %}" class="w3-button w3-blue-grey w3-hover-purple w3-large w3-round">Cancel</a>
			{% if item %}
				<button class="w3-button w3-green w3-border w3-hover-purple w3-large w3-round"  type="submit">Confirm</button>
			{% else %}
				<button class="w3-button w3-green w3-border w3-hover-purple w3-large w3-round"  type="submit">Add New Task</button>
			{% endif %}
			
		</div>
	</form>
</div>
	
{% endblock %}

mysite/taskmaster/templates/taskmaster/master.html
{% extends 'taskmaster/base.html' %}

{% block pagetitle %}
	Masterlists
{% endblock %}

{% block pagename %}
	<span class="w3-badge w3-xlarge w3-deep-purple">
        😎
    </span>
    <span class="w3-text-deep-purple">
        <b>{{user.username|capfirst}}</b>
    </span>
{% endblock %}

{% block info %}
    <div class="w3-panel w3-round w3-border w3-padding w3-text-deep-purple">
        <h3><b>
        {% if time.hour < 12 %}
            Good morning
        {% elif time.hour <= 17 %}
            Good Afternoon
        {% else %}
            Good Evening
        {% endif %}
        , {{user.username|capfirst}}
        </b></h3>
        <div class="w3-leftbar w3-border-green w3-pale-green w3-round w3-padding">
        This is where you can view and edit all of your <b>Masterlists</b>.
        </div>
    </div>
{% endblock info %}

{% block content %}
<div class="w3-display-container w3-bottombar w3-border-deep-purple">
    <h3 class="w3-text-deep-purple">📒 Masterlists</h3>
    <a href="{% url 'taskmaster:master_create' %}" class="w3-btn w3-round w3-deep-purple w3-border w3-border-deep-purple w3-hover-white w3-display-right">+ Add New List
    </a>
</div>

{% if masters %}
    <div class="w3-row-padding w3-container w3-light-grey" style="height:300px;overflow-y:scroll">
    {% for list in masters %}
    	<div class="w3-col l4 w3-section">
    		<a href="{% url 'taskmaster:master_detail' list.id %}" 
      	class=" w3-card w3-button w3-round w3-topbar w3-border-amber  w3-hover-pale-yellow w3-white" style="width:100%">
      			<h3 class="w3-text-deep-purple"><b>{{list.name}}</b></h3>
      		</a>
    	</div>
    {% endfor %}
    </div>
{% else %}
    <div class="w3-panel w3-yellow w3-leftbar w3-border-amber w3-large w3-round">
        <p>You don't have any master list yet. Click <span class="w3-tag w3-deep-purple w3-round">+ AddNewList</span> button to add new masterlist.</p>
    </div>	
{% endif %}

{% endblock %}

mysite/taskmaster/templates/taskmaster/todolist_detail.html
{% extends 'taskmaster/base.html' %}
{% block pagetitle %}
    {{todolist.name}}
{% endblock %}

{% block pagename %}
    <span class="w3-badge w3-xlarge w3-deep-purple">
        😎
    </span>
    <span class="w3-text-deep-purple">
        <b>{{user.username|capfirst}}</b>
    </span>
{% endblock %}

{% block info %}
    <div class="w3-panel w3-round w3-border w3-padding w3-text-deep-purple">
        <h3><b>
        {% if time.hour < 12 %}
            Good morning
        {% elif time.hour <= 17 %}
            Good Afternoon
        {% else %}
            Good Evening
        {% endif %}
        , {{user.username|capfirst}}
        </b></h3>
        <div class="w3-leftbar w3-border-green w3-pale-green w3-round w3-padding">
            All tasks inside <b>{{todolist.name}}</b> masterlist can be seen on this page.
        </div>
    </div>
{% endblock info %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="w3-display-container  w3-bottombar w3-border-deep-purple">
        <div class="w3-dropdown-hover w3-white">
            <h2 class="w3-text-deep-purple">📝{{todolist.name}}</h2>
            <div class="w3-dropdown-content w3-bar-block w3-border w3-border-amber w3-topbar w3-padding">
                <a href="{% url 'taskmaster:master_update' todolist.id %}" class="w3-btn w3-bar-item w3-deep-purple w3-round w3-border w3-hover-white">Rename</a>
                <a href="{% url 'taskmaster:master_delete' todolist.id %}" class="w3-btn w3-bar-item w3-pink w3-round w3-border w3-hover-white">Delete</a>
            </div>
        </div>
        <button type="submit" class="w3-btn w3-round w3-deep-purple w3-border w3-border-deep-purple w3-hover-white w3-display-right" name="update" value="true">Update</button>
    </div>
    {% if todolist.item_set.all|length %}
        <div class="w3-row-padding w3-light-grey" style="height:300px;overflow-y:scroll">
            {% for task in todolist.item_set.all %}
            <div class="w3-col l6">
                <div class="w3-container w3-card w3-white w3-round w3-section w3-padding w3-text-deep-purple">
                    {% if task.complete %}
                        <input class="w3-check" type="checkbox" name="t{{task.id}}" checked>
                    {% else %}
                        <input class="w3-check" type="checkbox" name="t{{task.id}}">
                    {% endif %}
                    <a href="{% url 'taskmaster:task_detail' task.id %}" class=" w3-xlarge w3-margin-left">
                        <b>{{task.name}}</b>
                    </a>
                    <span class="w3-tag w3-round w3-pink w3-right w3-xlarge">{{task.priority}}</span>
                    <div class="w3-cell-row w3-round w3-border w3-section" style="width:80%;margin:auto">
                        <span class="w3-cell w3-light-grey w3-padding">
                            ⏰
                        </span>
                        <span class="w3-cell w3-padding">
                            <b>{{task.due_date}}</b>
                        </span>
                    </div>
                </div>     
            </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="w3-panel w3-yellow w3-leftbar w3-border-amber">
            <p>You don't have any task added yet. Click <span class="w3-tag w3-deep-purple w3-round">+NewTask</span> button to add new task.</p>
        </div>
    {% endif %}
</form>

{% endblock %} 